### ISSUE TITLE
DOM is overwhelmed by residual .smoke-base elements

### ISSUE THREAD

**Issue by ThomasPerraudin** [hxgf/smoke.js#51]
I use smoke.js in a web app (with no page reload in a full day time). Each time smoke is used, it adds a new element to the body. This kind of element :

`<div id="smoke-out-1428659028629.3865" class="smoke-base" style="z-index: 1000;"></div>`

To keep a clean DOM and for performance reasons I would like to get read of these elements. Could this be done automatically each time the alert is closed ?

**Comment by hxgf** [comment]
let's just take a second to appreciate the irony of a library called "smoke" choking the DOM.

you're totally right, though...i'm not sure why it wasn't being cleaned up in the first place. i'll update it when i get a chance.

*(or anyone else is welcome to and i'll merge it in...line 403 needs to remove the "box" DOM element instead of making it empty)*
